Fixed #23
poggit-orphanage/WorldProtect pull request #24
Opened 2021-12-26 02:57 UTC by supercrafter333

2021-12-26 15:35 UTC, supercrafter333 commented
@SOF3

2021-12-26 16:03 UTC, SOF3 requested changes

2021-12-26 16:03 UTC, SOF3 commented on src/aliuly/worldprotect/WpProtectMgr.php
> +						$player = $this->owner->getServer()->getPlayerExact($i);
Isn't it supposed to be by prefix?

2021-12-26 16:22 UTC, supercrafter333 commented on src/aliuly/worldprotect/WpProtectMgr.php
> +						$player = $this->owner->getServer()->getPlayerExact($i);
Hmm... Yes?

2021-12-26 16:24 UTC, supercrafter333 commented
Now it's finished @SOF3

2021-12-27 04:10 UTC, SOF3 approved these changes

2021-12-27 04:10 UTC, merged